from .day_1 import Day1
from .day_2 import Day2
from .day_3 import Day3
from .day_4 import Day4
from .day_5 import Day5
from .day_6 import Day6
from .day_7 import Day7
from .day_8 import Day8
from .day_9 import Day9
